# Generated by Django 4.0.4 on 2022-07-11 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=None, default='현우', max_length=50, null=True)),
                ('age', models.IntegerField(blank=None, default=0, null=True)),
                ('phone', models.IntegerField(blank=None, default=0, null=True)),
            ],
        ),
    ]
