# Generated by Django 4.0.4 on 2022-08-02 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todomate', '0002_todo'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeLion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20, unique=True)),
                ('age', models.CharField(choices=[('기획', '기획'), ('백엔드', '백엔드'), ('프론트', '프론트')], max_length=20)),
            ],
        ),
    ]
