# Generated by Django 4.0.4 on 2022-08-02 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Generics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20, unique=True)),
                ('part', models.CharField(choices=[('에시공', '에시공'), ('소프트', '소프트')], default='백엔드', max_length=20)),
                ('age', models.IntegerField(default=20)),
                ('bio', models.TextField(default='소개를 입력하라.', null=True)),
                ('profile_image', models.ImageField(blank=True, max_length=5, null=True, upload_to='')),
            ],
        ),
    ]
